language: php

php:
  - 7.2
  - 7.3
  - 7.4

services:
  - mysql

before_install:
  - composer self-update

install:
  - composer install --dev --no-interaction

before_script:
  - mysql -u root -e "create database test"
  - mkdir -p build/logs

script:
  - composer lint
  - composer findbug
  - composer test

after_success:
  - travis_retry php vendor/bin/php-coveralls
